/********************************************************************
* dict/ConfigParserDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/ConfigParserDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableConfigParserDict();
extern void G__cpp_setup_inheritanceConfigParserDict();
extern void G__cpp_setup_typetableConfigParserDict();
extern void G__cpp_setup_memvarConfigParserDict();
extern void G__cpp_setup_globalConfigParserDict();
extern void G__cpp_setup_memfuncConfigParserDict();
extern void G__cpp_setup_funcConfigParserDict();
extern void G__set_cpp_environmentConfigParserDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/marco/script/RootUtils/src/ConfigParser.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ConfigParserDictLN_TClass;
extern G__linked_taginfo G__ConfigParserDictLN_TBuffer;
extern G__linked_taginfo G__ConfigParserDictLN_TMemberInspector;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_string;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConfigParserDictLN_ConfigParser;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConfigParserDictLN_vectorlEOptionlEstringgRcOallocatorlEOptionlEstringgRsPgRsPgR;
extern G__linked_taginfo G__ConfigParserDictLN_reverse_iteratorlEvectorlEOptionlEstringgRcOallocatorlEOptionlEstringgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
