/********************************************************************
* dict/PlotUtilsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict/PlotUtilsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePlotUtilsDict();
extern void G__cpp_setup_inheritancePlotUtilsDict();
extern void G__cpp_setup_typetablePlotUtilsDict();
extern void G__cpp_setup_memvarPlotUtilsDict();
extern void G__cpp_setup_globalPlotUtilsDict();
extern void G__cpp_setup_memfuncPlotUtilsDict();
extern void G__cpp_setup_funcPlotUtilsDict();
extern void G__set_cpp_environmentPlotUtilsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/marco/script/RootUtils/src/PlotUtils.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PlotUtilsDictLN_TClass;
extern G__linked_taginfo G__PlotUtilsDictLN_TBuffer;
extern G__linked_taginfo G__PlotUtilsDictLN_TMemberInspector;
extern G__linked_taginfo G__PlotUtilsDictLN_TObject;
extern G__linked_taginfo G__PlotUtilsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PlotUtilsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlotUtilsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PlotUtilsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlotUtilsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PlotUtilsDictLN_TH1;
extern G__linked_taginfo G__PlotUtilsDictLN_RooPlot;
extern G__linked_taginfo G__PlotUtilsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PlotUtilsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PlotUtilsDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__PlotUtilsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__PlotUtilsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlotUtilsDictLN_TCanvas;
extern G__linked_taginfo G__PlotUtilsDictLN_ColorPalette;
extern G__linked_taginfo G__PlotUtilsDictLN_PlotUtils;
extern G__linked_taginfo G__PlotUtilsDictLN_vectorlERooPlotmUcOallocatorlERooPlotmUgRsPgR;
extern G__linked_taginfo G__PlotUtilsDictLN_reverse_iteratorlEvectorlERooPlotmUcOallocatorlERooPlotmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlotUtilsDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__PlotUtilsDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
